### ISSUE TITLE
Incorrect answer for question 46

### ISSUE THREAD

**Issue by stefanhuber** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#10]
I think `Blue-Green Deployment` is considered a DevOps practice. E.g., it is mentioned in the [AWS DevOps Guide](https://docs.aws.amazon.com/whitepapers/latest/introduction-devops-aws/blue-green-deployments.html)

**Comment by danieldanielecki** [comment]
@stefanhuber, correct :)
Fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/f7b739e7fe368be813d4b35d373b7fe7f0a799e3.

**Comment by stefanhuber** [comment]
@danieldanielecki I think both answers are correct though. Since CI/CD are also DevOps prqctices of course...

**Comment by kassiakom** [comment]
@stefanhuber I agree with you, both options are correct. Maybe the right answer is option: All of the above. @danieldanielecki

**Comment by danieldanielecki** [comment]
Improved in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/f7b84531e10e9bb356dff55c53c7d8813a190fc3
