### ISSUE TITLE
Contradicting answers for question 208 and 269

### ISSUE THREAD

**Issue by stefanhuber** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#11]
Regarding the answer `Code Coverage` once it is considered a code metric and once it is not.

**Comment by danieldanielecki** [comment]
Fixed in hich of the following are NOT metrics of Code Quality?

**Comment by lin-naingoo** [comment]
Code Coverage is not code metric. 208 should be fixed instead.

This is feedback from Scrum Developer Open.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/97221082/210040703-473771cc-8653-43d9-a8d6-095519018afc.png">

**Comment by danieldanielecki** [comment]
Improved in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/f7b84531e10e9bb356dff55c53c7d8813a190fc3

**Comment by danieldanielecki** [comment]
> Fixed in [5189dfa](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/5189dfac3b8b5ef15ca759cf6975ef6a72ed284b)

I'm only wondering now if this change was correct hmm

**Comment by danieldanielecki** [comment]
Reverted in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/b1390c7c322fdb37a9215d446ddc29c0bbc3a60b
