### ISSUE TITLE
Typo in 48: What tactic should a Scrum Master use to divide a group of 100 people into multiple Scrum Teams?

### ISSUE THREAD

**Issue by mobidroid92** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#20]
Ask the people to divide themselves "info" teams.
"info" should be "into"

**Comment by danieldanielecki** [comment]
Sharp eye @mobidroid92, fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/4fde77579711af8dd0948c632828940631f529f3; thanks!
