### ISSUE TITLE
Wrong answer "In an impediment case, the Scrum Master can intervene to help the Development Team to remove a member from the Development Team."

### ISSUE THREAD

**Issue by noubar** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#22]
In an impediment case, the Scrum Master can intervene to help the Development Team to remove a member from the Development Team.
The answer is True?
It should be false, because Scrum master cannot remove a member from a team. Has no authority to do so.

Alternatively:
Maybe the question has misspelling and meant to remove an impediment rather than the member in the following form:
In an impediment case, the Scrum Master can intervene to help the Development Team to remove the impediment from the Development Team.

**Comment by danieldanielecki** [comment]
@noubar, thanks for the question. However, the current answer is marked correctly and it's indeed `True.` for the question 229 https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#true-or-false-in-an-impediment-case-the-scrum-master-can-intervene-to-help-the-development-team-to-remove-a-member-from-the-development-team.

I do have a nice discussion reference for you!:)
https://www.scrum.org/forum/scrum-forum/31248/when-development-team-member-becomes-impediment-does-scrum-master-or-whole
