### ISSUE TITLE
Question 226 - Which is true about the Sprint Backlog?

### ISSUE THREAD

**Issue by zhongdeliu** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#24]
In my opinion, answer 1 should also be a correct answer, no?

>  It is a list of selected Product Backlog Items that the Development Team has committed for the Sprint.

Any explanation would be highly appreciated :)

**Comment by danieldanielecki** [comment]
@zhongdeliu please read https://www.scrum.org/resources/blog/scrum-myth-sprint-backlog-commitment :)

The current answer stays.
