### ISSUE TITLE
Grammar issues throughout practice tests - test #3 in particular

### ISSUE THREAD

**Issue by petunia-picker** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#25]
All of the practice tests need to be reviewed and updated by a native English speaker with an understanding of Scrum - test 3 in particular - some of the questions and answers make no sense

**Comment by danieldanielecki** [comment]
@petunia-picker, the issue is too general. Kindly please create and propose your improvement in a more concrete way, preferably a Pull Request (PR).

**Comment by petunia-picker** [comment]
look at question #240 - the correct answer is "none" but the given choice is "no one"

this is the most blatant example of poor grammar / lack of review - other instances exist throughout all 4 tests

as a user of the product, my confidence in the product is reduced each time I see errors like this

**Comment by petunia-picker** [comment]
look at question #212 - the correct answer is "Inform the Product Owner" but the choice given is "Inform the Product Owner to work with his/her."

another choice given is "Inform the Scrum Master to work with his/her."

these choices are nonsensical
