### ISSUE TITLE
New questions from test made on 23 out. 2023

### ISSUE THREAD

**Issue by phellipelins** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#26]
I'm not sure if I checked the correct answers, but I had 92.7% positive on the test.

![Question 1](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/ca0b1d66-7947-448c-a968-ce8bb670e28c)
![Question 2](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/5ee4b450-0bb3-45c0-9ed3-46896671a387)
![Question 3](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/ad7e0cee-2d02-45de-a346-b56347ce1797)
![Question 4](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/bcd93b44-7943-447e-a249-279c9a14feea)
![Question 5](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/c61f219a-27b3-4d44-8c5f-1e7ec99c42a8)
![Question 6](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/6606d957-d180-4a9d-ae67-e3847261f737)
![Question 7](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/cbad6760-172c-40f7-a5f1-4a22fa62aa36)
![Question 8](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/757c827f-ff51-49b6-b5cb-01386c419ec8)
![Question 9](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/e9252a5c-872e-4bf5-8c52-832ab5fefcf9)
![Question 10](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/assets/127338268/2de8d9c0-5f04-4256-89c9-7a8fb9f3562e)

**Comment by danieldanielecki** [comment]
Hello, please don't send such materials here. As far as I'm aware, it's not allowed to screenshot these exams. I'm closing the issue, but I'd appreciate completely deleting it. If you have some new content, you can always submit a Pull Request. Thanks
