### ISSUE TITLE
Efferent Coupling

### ISSUE THREAD

**Issue by rcmedeiros** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#27]
Hi.

First I wanna say that I really enjoyed this repo, going through such exercises is precisely my learning style. 

Now about the issue:

```
Which is NOT true about Efferent Coupling?
1. [   ] Classes with high efferent will affect other classes when changes are made.
2. [   ] A large Efferent Coupling can indicate that a class is unfocused and may also indicate that it is unstable since it depends on the stability of all the types to which it is coupled.
3. [ x ] Classes with high Efferent Coupling will receive the effects of changes or defects in other classes.
4. [   ] It is a Code Quality metric.
```
The answer is actually inverted. If a class has a high efferent coupling, it means it has lots of dependencies. thus..
* option 1 is not true and **should** be marked, because the class being measured has no influence over its dependencies;
* option 2 is true;
* option 3 is true and **should not** be marked, because the class being measured will be affected by chances or defects in classes it depends on;
* option 4 is true.

**Comment by danieldanielecki** [comment]
@rcmedeiros, thanks.

I also read the article: https://www.informit.com/articles/article.aspx?p=1561879&seqNum=3, and it seems to me the keyword here is *affect*; if it would be *receive*, then it would be true.

_"Efferent coupling measures the number of classes on which a given class depends. A good way to remember efferent (versus afferent) is that classes with high efferent coupling will receive the effects of changes or defects in other classes."_
