### ISSUE TITLE
Answer to question seems wrong: "Which of the following describes the focus of the first way of DevOps?"

### ISSUE THREAD

**Issue by 3ter** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#28]
The question in question:
https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/blob/3e2dc27e23ff67ff2fda3069bdc21a20c339bbc2/README.md?plain=1#L913-L919

While release pipelines are indeed an important tool, the focus should be `To deliver value earlier and more frequently.`. See for example [gitlab](https://about.gitlab.com/blog/2022/06/15/gitlab-and-the-three-ways-of-devops/#:~:text=The%20First%20Way%20is%20all%20about%20making%20work/value%20flow%20better%20through%20the%20whole%20value%20stream%20(left%20to%20right)%2C%20and%20to%20do%20that%2C%20we%20need%20to%20have%20a%20systems%20thinking%20approach%20and%20always%20look%20at%20the%20end%2Dto%2Dend%20result.).

**Comment by danieldanielecki** [comment]
I agree, fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/620ff87de4d949ec65355969604703bdcaf218d4; thanks!
