### ISSUE TITLE
Wrong answers for 227

### ISSUE THREAD

**Issue by ByteBeatBit** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#29]
Hi, i'm supposing that 227 has wrong answers. 
The question is: 
Which one is true about Definition of Done and Acceptance Criteria?
current answers are:
- [ ] Acceptance Criteria should be passed for a feature in order to be called as complete and done.
- [x] Acceptance Criteria should be passed to ensure that a feature is working as expected.
- [x] Definition of Done should be applied to a feature in order to be called as complete.
- [x] There are many Acceptance Criteria in a Product.
- [ ] There are many Definition of Done in a Product and a Scrum Team.

but:
• Acceptance Criteria should be passed for a feature in order to be called as complete and done: should be right because AC are conditions that need to be satisfied to be accepted from PO and stakeholders. AC are part of DoD that define a completed and working task. 
•  There are many Definition of Done in a Product and a Scrum Team: this should be wrong, Dod is unique for a Product and a Scrum Team. Dod Should be common and recognized from all Scrum Team members, and must be coherent with the product, many DoD cause confusion, inconsistency and ambiguity.
•  There are many Acceptance Criteria in a Product: this should be wrong, AC are specific for every PBI, not for product. Every PBI has their AC, but the product didn't have AC, but has a vision, a target and a value. 

sorry my bad english, hope is understandable.

**Comment by danieldanielecki** [comment]
@ByteBeatBit thanks a lot, fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/7b9e729a1af98b509f9db60d340e94e9c88a4531!

PS. Your English is better than you're thinking! ;-)
