### ISSUE TITLE
Incorrect answer on "What are two ways that regulatory compliance issues are dealt with in Scrum?"?

### ISSUE THREAD

**Issue by chrismaandhika** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#8]
![image](https://user-images.githubusercontent.com/5126089/208358036-f0aade49-49d6-426e-bc24-39e9e79dce9c.png)

From many other sources, the fourth choice is part of the answer, while third choice is not. 
Should we consider fourth choice instead of third choice as part of the answer?

**Comment by danieldanielecki** [comment]
Kindly please submit a PR.

**Comment by danieldanielecki** [comment]
Wasn't sure about it, but yes - fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/46aa9b718ec17f4d3cc408877a9e37002c35ff84.
