### ISSUE TITLE
Incorrect answer on "Which of the following describe Test Driven Development? (choose two answers)"?

### ISSUE THREAD

**Issue by chrismaandhika** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#9]
![image](https://user-images.githubusercontent.com/5126089/208375757-05f7080b-f587-45a5-a1a7-1515af02a65f.png)

The answer of the question above might be the first and fourth choices, not including the second choice.

This is related to other question, "True or False: Test-Driven Development is a predictable way to develop working, well-organized code?", as this other question has False as its answer. So, it might be contradict with the first question.

**Comment by kycnexynpuwejl** [comment]
agree with @chrismaandhika

**Comment by danieldanielecki** [comment]
Kindly please submit a PR.

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/4d56403f9d4bbb20f0df95e4774994f8a661edcb.

**Comment by lin-naingoo** [comment]
Contradicting answer on question 256 "What is NOT Test Driven Development?"

The answer should be 1 and 4.
1. A predictable way to develop working, clean code.
2. A Software Development technique based on automated tests.
3. An incremental and emergent approach to Software Design.
4. Testing existing Software before developing any new Software.

**Comment by danieldanielecki** [comment]
Improved in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/f7b84531e10e9bb356dff55c53c7d8813a190fc3
